# 넘파이

### 1. 넘파이 가져오기

In [1]:
import numpy as np

### 2. 넘파이 배열 생성하기

In [3]:
# 넘파이 배열을 만들 때는 np.array() 메서드를 이용한다.
# np.array()는 파이썬의 리스트를 인수로 받아 넘파이 라이브러리가 제공하는 특수한 형태의 배열(numpy.ndarray)을 반환한다.

x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

### 3. 넘파이의 산술 연산

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
x + y

array([3., 6., 9.])

In [5]:
x - y

array([-1., -2., -3.])

In [6]:
x * y

array([ 2.,  8., 18.])

In [7]:
x / y

array([0.5, 0.5, 0.5])

### 4. 넘파이의 N차원 배열

In [8]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [10]:
A.shape

(2, 2)

In [11]:
A.dtype

dtype('int32')

In [15]:
# 2차원 배열 A와 B의 산술 연산을 진행해보자.
B = np.array([[3, 0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [16]:
A * B

array([[ 3,  0],
       [ 0, 24]])

In [17]:
print(A)

[[1 2]
 [3 4]]


In [18]:
A * 10

array([[10, 20],
       [30, 40]])